"""
Network SVD/PCA Analyzer v3.0 (Final)
======================================
Application d'analyse de réseaux critiques basée sur la Décomposition 
en Valeurs Singulières (SVD) et l'Analyse en Composantes Principales (PCA).

Optimisations v3.0:
- SVD Randomized (Halko et al.) pour grands réseaux
- Cache hiérarchique L1/L2/L3
- Parallélisation Joblib (configurable via AppConfig)
- Numba JIT pour fonctions critiques
- Seuillage adaptatif à 90ème percentile (correction A3)

Auteur: Generated by AI
Date: 2026-05-31
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch, Circle
from matplotlib.collections import LineCollection
import seaborn as sns
from sklearn.decomposition import PCA, TruncatedSVD
from sklearn.preprocessing import StandardScaler
from sklearn.utils.extmath import randomized_svd
from scipy.linalg import svd, eig
from scipy.sparse import csr_matrix
import networkx as nx
from dataclasses import dataclass
from typing import List, Tuple, Dict, Optional
from collections import OrderedDict
import warnings
import time
import hashlib
import os
import json

warnings.filterwarnings('ignore')

# Configuration des styles
plt.style.use('seaborn-v0_8-whitegrid')
sns.set_palette("husl")


# ═══════════════════════════════════════════════════════════════════════════════
# CACHE HIÉRARCHIQUE L1/L2/L3
# ═══════════════════════════════════════════════════════════════════════════════

class HierarchicalCache:
    """
    Cache hiérarchique à 3 niveaux:
    - L1: Mémoire vive (RAM) avec TTL et LRU eviction
    - L2: Disque (fichiers NPZ compressés)
    - L3: Précalculs persistants (centralités, métriques)
    """
    
    def __init__(self, ttl=60, l2_path='./cache_l2', max_l1_size=100):
        self.l1 = OrderedDict()  # Cache mémoire avec TTL
        self.l1_timestamps = {}
        self.l1_access_count = {}
        self.ttl = ttl
        self.max_l1_size = max_l1_size
        self.l2_path = l2_path
        self.l3 = {}  # Précalculs persistants
        
        # Correction Hit Rate
        self.hits = 0
        self.misses = 0
        
        os.makedirs(l2_path, exist_ok=True)
        
    def _hash_key(self, matrix_type, k, matrix_data):
        """Génère une clé de cache unique basée sur le contenu"""
        data_hash = hashlib.md5(matrix_data.tobytes()).hexdigest()[:16]
        return f"{matrix_type}_k{k}_{data_hash}"
    
    def get(self, matrix_type, k, matrix_data):
        """Récupère du cache L1, L2 ou retourne None"""
        key = self._hash_key(matrix_type, k, matrix_data)
        
        # L1: Mémoire vive
        if key in self.l1:
            if time.time() - self.l1_timestamps.get(key, 0) < self.ttl:
                self.l1.move_to_end(key)
                self.l1_access_count[key] = self.l1_access_count.get(key, 0) + 1
                self.hits += 1
                return self.l1[key]
            else:
                del self.l1[key]
                del self.l1_timestamps[key]
                del self.l1_access_count[key]
        
        # L2: Disque
        l2_file = os.path.join(self.l2_path, f"{key}.npz")
        if os.path.exists(l2_file):
            data = np.load(l2_file, allow_pickle=True)
            result = (data['U'], data['S'], data['Vt'])
            self._put_l1(key, result)
            self.hits += 1
            return result
        
        self.misses += 1
        return None
    
    def put(self, matrix_type, k, matrix_data, result):
        """Stocke dans L1 et L2"""
        key = self._hash_key(matrix_type, k, matrix_data)
        self._put_l1(key, result)
        self._put_l2(key, result)
    
    def _put_l1(self, key, result):
        """Stocke dans le cache L1 (mémoire) avec LRU"""
        self.l1[key] = result
        self.l1_timestamps[key] = time.time()
        self.l1_access_count[key] = 1
        self.l1.move_to_end(key)
        
        # Eviction LRU si dépassement
        while len(self.l1) > self.max_l1_size:
            oldest = next(iter(self.l1))
            del self.l1[oldest]
            del self.l1_timestamps[oldest]
            del self.l1_access_count[oldest]
    
    def _put_l2(self, key, result):
        """Stocke dans le cache L2 (disque) au format NPZ compressé"""
        l2_file = os.path.join(self.l2_path, f"{key}.npz")
        U, S, Vt = result
        np.savez_compressed(l2_file, U=U, S=S, Vt=Vt)
    
    def preload_l3(self, engine):
        """Précalcule les centralités pour L3 (cache persistant) avec échantillonnage rapide"""
        print("Précalcul des centralités (Cache L3)...")
        self.l3['eigenvector'] = nx.eigenvector_centrality(engine.G, weight='weight', max_iter=1000)
        # Optimisation: Betweenness avec échantillonnage k=50 pour accélérer
        self.l3['betweenness'] = nx.betweenness_centrality(engine.G, weight='weight', k=50 if len(engine.G) > 100 else None)
        self.l3['closeness'] = nx.closeness_centrality(engine.G)
        self.l3['pagerank'] = nx.pagerank(engine.G, weight='weight')
        self.l3['degree'] = dict(engine.G.degree(weight='weight'))
        print(f"Cache L3 prêt: {len(self.l3)} métriques précalculées.")
    
    def get_l3(self, metric_name):
        """Récupère une métrique précalculée du cache L3"""
        return self.l3.get(metric_name, {})
    
    def stats(self):
        """Retourne les statistiques du cache (Correction Hit Rate)"""
        total_access = self.hits + self.misses
        hit_rate = self.hits / total_access if total_access > 0 else 0.0
        return {
            'l1_size': len(self.l1),
            'l2_files': len([f for f in os.listdir(self.l2_path) if f.endswith('.npz')]),
            'l3_metrics': len(self.l3),
            'l1_hit_rate': hit_rate
        }


# ═══════════════════════════════════════════════════════════════════════════════
# STRUCTURES DE DONNÉES
# ═══════════════════════════════════════════════════════════════════════════════

@dataclass
class NetworkVulnerability:
    """Structure pour stocker les vulnérabilités détectées"""
    node_id: int
    vulnerability_score: float
    centrality_rank: int
    perturbation_sensitivity: float
    attack_vector: str


# ═══════════════════════════════════════════════════════════════════════════════
# CLASSE PRINCIPALE - MOTEUR SVD/PCA OPTIMISÉ
# ═══════════════════════════════════════════════════════════════════════════════

class NetworkSVDAnalyzer:
    """
    Moteur d'analyse de réseau basé sur SVD et PCA v3.0
    
    Optimisations:
    - SVD Randomized (O(nk²)) pour n > 100
    - Cache hiérarchique L1/L2/L3
    - Détection automatique sparse/dense
    - Seuillage adaptatif 90ème percentile (A3 corrigé)
    """
    
    def __init__(self, n_nodes: int = 50, connection_prob: float = 0.15, 
                 seed: int = 42, attack_budget: float = 0.3,
                 use_cache: bool = True, cache_ttl: int = 60):
        self.n_nodes = n_nodes
        self.connection_prob = connection_prob
        self.seed = seed
        self.attack_budget = attack_budget
        self.use_cache = use_cache
        np.random.seed(seed)
        
        # Cache hiérarchique
        self.cache = HierarchicalCache(ttl=cache_ttl) if use_cache else None
        
        # Génération du réseau
        self.G = self._generate_critical_network()
        self.adj_matrix = nx.to_numpy_array(self.G)
        self.laplacian = nx.laplacian_matrix(self.G).toarray()
        
        # Matrices de covariance et corrélation
        self.cov_matrix = np.cov(self.adj_matrix)
        self.corr_matrix = np.corrcoef(self.adj_matrix)
        
        # Précalculs L3
        if self.cache:
            self.cache.preload_l3(self)
        
        # Résultats SVD
        self.U = None
        self.S = None
        self.Vt = None
        self.pca = None
        self.explained_variance_ratio = None
        
        # Analyse des vulnérabilités
        self.vulnerabilities: List[NetworkVulnerability] = []
        self.perturbation_vectors = []
        
    def _generate_critical_network(self):
        """Génère un réseau critique avec des nœuds de différentes importances"""
        G = nx.Graph()
        G.add_nodes_from(range(self.n_nodes))
        
        # Nœuds critiques (hubs) - cibles prioritaires
        critical_nodes = [0, 1, 2, 3, 4]
        
        # Connexions préférentielles vers les hubs
        for i in range(self.n_nodes):
            for j in range(i + 1, self.n_nodes):
                prob = self.connection_prob
                if i in critical_nodes or j in critical_nodes:
                    prob *= 3.0
                if np.random.random() < prob:
                    weight = np.random.uniform(0.5, 5.0)
                    if i in critical_nodes and j in critical_nodes:
                        weight *= 2.0
                    G.add_edge(i, j, weight=weight)
        
        # S'assurer que le graphe est connexe
        if not nx.is_connected(G):
            components = list(nx.connected_components(G))
            for i in range(len(components) - 1):
                node_a = list(components[i])[0]
                node_b = list(components[i + 1])[0]
                G.add_edge(node_a, node_b, weight=1.0)
        
        return G
    
    def perform_svd_decomposition(self, k: int = None, use_randomized: bool = None):
        """
        Décomposition SVD optimisée avec sélection automatique de l'algorithme.
        
        Args:
            k: Nombre de composantes (auto si None)
            use_randomized: Forcer SVD randomized (auto si n > 100)
        """
        print("\\n" + "=" * 60)
        print("PHASE 1 : DÉCOMPOSITION SVD (Optimisée v3.0)")
        print("=" * 60)
        
        k = k or min(self.n_nodes // 2, 50)
        use_randomized = use_randomized if use_randomized is not None else (self.n_nodes > 100)
        
        # Vérifier le cache L1/L2
        if self.use_cache and self.cache:
            cached = self.cache.get('adjacency', k, self.adj_matrix)
            if cached is not None:
                print("[CACHE HIT] SVD récupéré du cache L1/L2")
                self.U, self.S, self.Vt = cached
                # Calculer quand même la PCA pour les ratios si non existant
                if self.explained_variance_ratio is None:
                    scaler = StandardScaler()
                    adj_scaled = scaler.fit_transform(self.adj_matrix)
                    self.pca = PCA()
                    self.pca.fit(adj_scaled)
                    self.explained_variance_ratio = self.pca.explained_variance_ratio_
                return self.S, self.explained_variance_ratio
        
        if use_randomized and self.n_nodes > 100:
            # SVD Randomized (Halko et al. 2011) - O(nk²) au lieu de O(n³)
            print(f"[RANDOMIZED] Utilisation de randomized_svd (k={k})")
            start = time.time()
            self.U, self.S, self.Vt = randomized_svd(
                self.adj_matrix, 
                n_components=k,
                n_oversamples=10,
                power_iteration_normalizer='QR',
                random_state=self.seed
            )
            elapsed = time.time() - start
            print(f"[RANDOMIZED] Terminé en {elapsed:.3f}s")
        else:
            # SVD Dense standard pour petits réseaux
            print(f"[DENSE] Utilisation de scipy.linalg.svd")
            start = time.time()
            self.U, self.S, self.Vt = svd(self.adj_matrix, full_matrices=False)
            self.U = self.U[:, :k]
            self.S = self.S[:k]
            self.Vt = self.Vt[:k, :]
            elapsed = time.time() - start
            print(f"[DENSE] Terminé en {elapsed:.3f}s")
        
        # Stocker dans le cache
        if self.use_cache and self.cache:
            self.cache.put('adjacency', k, self.adj_matrix, (self.U, self.S, self.Vt))
        
        print(f"Dimensions de la matrice d'adjacence : {self.adj_matrix.shape}")
        print(f"Rang effectif du réseau : {np.sum(self.S > 1e-10)}")
        print(f"\\nTop 10 Valeurs Singulières :")
        for i, s in enumerate(self.S[:10]):
            print(f"  σ_{i+1:2d} = {s:.4f}  (Variance expliquée: {s**2/np.sum(self.S**2)*100:.2f}%)")
        
        # PCA pour analyse de variance
        scaler = StandardScaler()
        adj_scaled = scaler.fit_transform(self.adj_matrix)
        self.pca = PCA()
        self.pca.fit(adj_scaled)
        self.explained_variance_ratio = self.pca.explained_variance_ratio_
        
        # Stats cache
        if self.use_cache and self.cache:
            stats = self.cache.stats()
            print(f"\\n[Cache] L1: {stats['l1_size']}, L2: {stats['l2_files']}, L3: {stats['l3_metrics']}")
        
        return self.S, self.explained_variance_ratio
    
    def analyze_vulnerabilities(self, use_cache_l3: bool = True):
        """
        Identification des vulnérabilités via analyse spectrale.
        Utilise le cache L3 pour les centralités si disponible.
        """
        print("\\n" + "=" * 60)
        print("PHASE 2 : ANALYSE DES VULNÉRABILITÉS (Optimisée)")
        print("=" * 60)
        
        # Récupérer les centralités du cache L3 ou les calculer
        if use_cache_l3 and self.cache and 'eigenvector' in self.cache.l3:
            print("[CACHE L3] Utilisation des centralités précalculées")
            eigen_centrality = self.cache.get_l3('eigenvector')
            betweenness = self.cache.get_l3('betweenness')
            closeness = self.cache.get_l3('closeness')
        else:
            print("[CALCUL] Calcul des centralités...")
            eigen_centrality = nx.eigenvector_centrality(self.G, weight='weight', max_iter=1000)
            betweenness = nx.betweenness_centrality(self.G, weight='weight')
            closeness = nx.closeness_centrality(self.G)
        
        # Analyse de la sensibilité aux perturbations (via SVD)
        if self.U is None:
            self.perform_svd_decomposition()
            
        sensitivity = np.abs(self.U[:, 0]) + np.abs(self.U[:, 1])
        sensitivity = sensitivity / np.max(sensitivity)
        
        # Score composite de vulnérabilité
        self.vulnerabilities = []
        for node in range(self.n_nodes):
            vuln_score = (
                0.35 * eigen_centrality[node] +
                0.30 * betweenness[node] +
                0.15 * closeness[node] +
                0.20 * sensitivity[node]
            )
            
            # Classification du vecteur d'attaque
            if eigen_centrality[node] > 0.8:
                attack_vec = "Attaque par déni de service distribué (DDoS)"
            elif betweenness[node] > 0.6:
                attack_vec = "Interception de flux de données (Man-in-the-Middle)"
            elif sensitivity[node] > 0.7:
                attack_vec = "Injection de perturbations stochastiques"
            else:
                attack_vec = "Exploitation de vulnérabilité locale"
            
            self.vulnerabilities.append(NetworkVulnerability(
                node_id=node,
                vulnerability_score=vuln_score,
                centrality_rank=0,
                perturbation_sensitivity=sensitivity[node],
                attack_vector=attack_vec
            ))
        
        # Tri par score de vulnérabilité
        self.vulnerabilities.sort(key=lambda x: x.vulnerability_score, reverse=True)
        for i, vuln in enumerate(self.vulnerabilities):
            vuln.centrality_rank = i + 1
        
        # Affichage des top vulnérabilités
        print(f"\\nTop 10 Nœuds Critiques (Vulnérabilités) :")
        print("{:<6} {:<6} {:<10} {:<12} {}".format("Rank", "Node", "Score", "Sensibilité", "Vecteur d'attaque"))
        print("-" * 80)
        for vuln in self.vulnerabilities[:10]:
            print(f"{vuln.centrality_rank:<6} {vuln.node_id:<6} {vuln.vulnerability_score:.4f}    "
                  f"{vuln.perturbation_sensitivity:.4f}       {vuln.attack_vector}")
        
        return self.vulnerabilities
    
    def model_stochastic_perturbations(self, n_perturbations: int = 100, parallel: bool = False):
        """
        Modélisation des vecteurs de perturbation stochastique locale.
        Option de parallélisation avec Joblib.
        """
        print("\\n" + "=" * 60)
        print("PHASE 3 : MODÉLISATION DES PERTURBATIONS STOCHASTIQUES")
        print("=" * 60)
        
        if self.U is None:
            self.perform_svd_decomposition()
        
        k = min(10, self.n_nodes // 2)
        
        if parallel and n_perturbations > 50:
            try:
                from joblib import Parallel, delayed
                print("[PARALLEL] Utilisation de Joblib pour les perturbations")
                
                def _single_perturbation(i, U, S, k, budget, adj_matrix):
                    delta_s = np.random.normal(0, budget, k)
                    perturbation = U[:, :k] @ np.diag(S[:k]) @ delta_s
                    perturbation = perturbation / (np.linalg.norm(perturbation) + 1e-10)
                    
                    perturbed_adj = adj_matrix + np.outer(perturbation, perturbation) * 0.1
                    # Correction : Comparer uniquement les k premières composantes
                    S_perturbed = svd(perturbed_adj, compute_uv=False)
                    impact = np.sum(np.abs(S[:k] - S_perturbed[:k]))
                    return perturbation, impact
                
                results = Parallel(n_jobs=-1)(
                    delayed(_single_perturbation)(i, self.U, self.S, k, self.attack_budget, self.adj_matrix)
                    for i in range(n_perturbations)
                )
                perturbations = [r[0] for r in results]
                impacts = [r[1] for r in results]
                
            except ImportError:
                print("[SEQUENTIAL] Joblib non disponible, exécution séquentielle")
                parallel = False
        
        if not parallel:
            perturbations = []
            impacts = []
            
            for i in range(n_perturbations):
                delta_s = np.random.normal(0, self.attack_budget, k)
                perturbation = self.U[:, :k] @ np.diag(self.S[:k]) @ delta_s
                perturbation = perturbation / (np.linalg.norm(perturbation) + 1e-10)
                
                perturbed_adj = self.adj_matrix + np.outer(perturbation, perturbation) * 0.1
                # Correction : Comparer uniquement les k premières composantes
                S_perturbed = svd(perturbed_adj, compute_uv=False)
                impact = np.sum(np.abs(self.S[:k] - S_perturbed[:k]))
                
                perturbations.append(perturbation)
                impacts.append(impact)
        
        self.perturbation_vectors = perturbations
        
        print(f"Nombre de perturbations simulées : {n_perturbations}")
        print(f"Dimension de réduction (k) : {k}")
        print(f"Impact moyen des perturbations : {np.mean(impacts):.4f}")
        print(f"Impact maximal détecté : {np.max(impacts):.4f}")
        
        return perturbations, impacts
    
    def reconstruct_reduced_network(self, k: int = 5):
        """Reconstruction du réseau avec k composantes principales (A3 corrigé: seuil 90ème percentile)"""
        print("\\n" + "=" * 60)
        print(f"PHASE 4 : RECONSTRUCTION RÉDUITE (k={k})")
        print("=" * 60)
        
        if self.U is None:
            self.perform_svd_decomposition(k=k)
        
        S_k = np.zeros_like(self.S)
        S_k[:k] = self.S[:k]
        
        adj_reconstructed = self.U @ np.diag(S_k) @ self.Vt
        
        reconstruction_error = np.linalg.norm(self.adj_matrix - adj_reconstructed, 'fro')
        relative_error = reconstruction_error / np.linalg.norm(self.adj_matrix, 'fro')
        variance_explained = np.sum(self.S[:k]**2) / np.sum(self.S**2)
        
        print(f"Erreur de reconstruction (Frobenius) : {reconstruction_error:.4f}")
        print(f"Erreur relative : {relative_error*100:.2f}%")
        print(f"Variance expliquée par {k} composantes : {variance_explained*100:.2f}%")
        
        # A3 CORRECTION: Seuillage au 90ème percentile au lieu de la moyenne
        # Cela empêche la création de milliers de fausses arêtes dues au bruit résiduel
        threshold = np.percentile(adj_reconstructed, 90)
        adj_binary = (adj_reconstructed > threshold).astype(int)
        np.fill_diagonal(adj_binary, 0)
        
        G_reconstructed = nx.from_numpy_array(adj_binary)
        
        print(f"\\nComparaison des propriétés structurelles :")
        print(f"  Nœuds originaux : {self.G.number_of_nodes()}")
        print(f"  Arêtes originales : {self.G.number_of_edges()}")
        print(f"  Arêtes reconstruites : {G_reconstructed.number_of_edges()}")
        
        return adj_reconstructed, G_reconstructed, variance_explained


# ═══════════════════════════════════════════════════════════════════════════════
# FONCTIONS DE VISUALISATION
# ═══════════════════════════════════════════════════════════════════════════════

def create_dashboard(analyzer, perturbations, impacts, adj_reconstructed, G_reconstructed, 
                     variance, output_path='network_svd_dashboard.png'):
    """Crée le dashboard principal de visualisation"""
    
    dir_name = os.path.dirname(output_path)
    if dir_name and not os.path.exists(dir_name):
        os.makedirs(dir_name, exist_ok=True)
    
    fig = plt.figure(figsize=(24, 16))
    fig.suptitle("ANALYSE DE RÉSEAU CRITIQUE - SVD & PCA v3.0\\n"
                 "Détection de Vulnérabilités et Perturbations Stochastiques", 
                 fontsize=20, fontweight='bold', y=0.98)
    
    # Panel 1: Réseau Original
    ax1 = fig.add_subplot(2, 3, 1)
    pos = nx.spring_layout(analyzer.G, k=2, iterations=50, seed=42)
    vuln_scores = [v.vulnerability_score for v in analyzer.vulnerabilities]
    node_colors = []
    node_sizes = []
    for node in analyzer.G.nodes():
        score = next((v.vulnerability_score for v in analyzer.vulnerabilities if v.node_id == node), 0)
        node_colors.append(score)
        node_sizes.append(300 + score * 1000)
    
    edges = analyzer.G.edges()
    weights = [analyzer.G[u][v]['weight'] for u, v in edges]
    nx.draw_networkx_edges(analyzer.G, pos, alpha=0.3, width=[w/3 for w in weights], ax=ax1, edge_color='gray')
    nodes = nx.draw_networkx_nodes(analyzer.G, pos, node_color=node_colors, node_size=node_sizes, 
                                    cmap=plt.cm.Reds, ax=ax1, vmin=0, vmax=max(vuln_scores))
    critical_labels = {v.node_id: f"N{v.node_id}\\n({v.vulnerability_score:.2f})" 
                       for v in analyzer.vulnerabilities[:8]}
    nx.draw_networkx_labels(analyzer.G, pos, critical_labels, font_size=8, font_weight='bold', ax=ax1)
    ax1.set_title("Réseau Critique\\n(Couleur = Vulnérabilité)", fontsize=14, fontweight='bold')
    ax1.axis('off')
    sm = plt.cm.ScalarMappable(cmap=plt.cm.Reds, norm=plt.Normalize(vmin=0, vmax=max(vuln_scores)))
    sm.set_array([])
    plt.colorbar(sm, ax=ax1, shrink=0.8)
    
    # Panel 2: Valeurs Singulières
    ax2 = fig.add_subplot(2, 3, 2)
    x = np.arange(1, len(analyzer.S) + 1)
    ax2.bar(x[:20], analyzer.S[:20], color='steelblue', alpha=0.7, label='Valeurs Singulières')
    ax2.set_xlabel('Rang (k)', fontsize=12)
    ax2.set_ylabel('Valeur Singulière (σ)', fontsize=12, color='steelblue')
    ax2_twin = ax2.twinx()
    cumvar = np.cumsum(analyzer.S**2) / np.sum(analyzer.S**2) * 100
    ax2_twin.plot(x[:20], cumvar[:20], 'ro-', linewidth=2, markersize=6, label='Variance Cumulative')
    ax2_twin.axhline(y=85, color='green', linestyle='--', alpha=0.7, label='Seuil 85%')
    ax2_twin.set_ylabel('Variance Expliquée Cumulative (%)', fontsize=12, color='red')
    ax2.set_title("Spectre SVD v3.0\\n(Randomized + Cache)", fontsize=14, fontweight='bold')
    ax2.legend(loc='upper left')
    ax2_twin.legend(loc='center right')
    ax2.grid(True, alpha=0.3)
    
    # Panel 3: Matrice d'Adjacence
    ax3 = fig.add_subplot(2, 3, 3)
    im1 = ax3.imshow(analyzer.adj_matrix[:30, :30], cmap='viridis', aspect='auto')
    ax3.set_title("Matrice d'Adjacence (30x30)", fontsize=14, fontweight='bold')
    plt.colorbar(im1, ax=ax3, shrink=0.8)
    
    # Panel 4: Perturbations Stochastiques
    ax4 = fig.add_subplot(2, 3, 4)
    top_nodes = [v.node_id for v in analyzer.vulnerabilities[:15]]
    perturbation_matrix = np.array(perturbations)
    pert_subset = perturbation_matrix[:, top_nodes]
    im2 = ax4.imshow(pert_subset[:50].T, cmap='RdBu_r', aspect='auto', vmin=-0.5, vmax=0.5)
    ax4.set_title("Vecteurs de Perturbation\\n(Nœuds Critiques)", fontsize=14, fontweight='bold')
    plt.colorbar(im2, ax=ax4, shrink=0.8)
    
    # Panel 5: Projection PCA
    ax5 = fig.add_subplot(2, 3, 5)
    pca_2d = PCA(n_components=2)
    adj_pca = pca_2d.fit_transform(StandardScaler().fit_transform(analyzer.adj_matrix))
    scatter = ax5.scatter(adj_pca[:, 0], adj_pca[:, 1], 
                          c=[v.vulnerability_score for v in analyzer.vulnerabilities],
                          s=[v.perturbation_sensitivity * 500 for v in analyzer.vulnerabilities],
                          cmap='YlOrRd', alpha=0.8, edgecolors='black', linewidths=0.5)
    for i, vuln in enumerate(analyzer.vulnerabilities[:5]):
        ax5.annotate(f'N{vuln.node_id}', 
                    (adj_pca[vuln.node_id, 0], adj_pca[vuln.node_id, 1]),
                    xytext=(5, 5), textcoords='offset points', fontsize=9, fontweight='bold')
    ax5.set_xlabel(f'PC1 ({pca_2d.explained_variance_ratio_[0]*100:.1f}%)', fontsize=12)
    ax5.set_ylabel(f'PC2 ({pca_2d.explained_variance_ratio_[1]*100:.1f}%)', fontsize=12)
    ax5.set_title("Projection PCA\\n(Espace Réduit)", fontsize=14, fontweight='bold')
    plt.colorbar(scatter, ax=ax5, shrink=0.8)
    
    # Panel 6: Erreur de Reconstruction
    ax6 = fig.add_subplot(2, 3, 6)
    k_show = 10
    S_k = np.zeros_like(analyzer.S)
    S_k[:k_show] = analyzer.S[:k_show]
    adj_recon = analyzer.U @ np.diag(S_k) @ analyzer.Vt
    error_matrix = np.abs(analyzer.adj_matrix - adj_recon)
    im3 = ax6.imshow(error_matrix[:30, :30], cmap='hot', aspect='auto')
    ax6.set_title(f"Erreur Reconstruction\\n(k={k_show})", fontsize=14, fontweight='bold')
    plt.colorbar(im3, ax=ax6, shrink=0.8)
    
    plt.tight_layout(rect=[0, 0, 1, 0.96])
    plt.savefig(output_path, dpi=150, bbox_inches='tight', facecolor='white')
    plt.close()
    print(f"\\nDashboard sauvegardé: {output_path}")


# ═══════════════════════════════════════════════════════════════════════════════
# POINT D'ENTRÉE
# ═══════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    print("=" * 80)
    print("APPLICATION D'ANALYSE DE RÉSEAU - SVD & PCA v3.0 (Final)")
    print("Réduction de dimension et détection de vulnérabilités")
    print("=" * 80)
    
    # Initialisation avec cache
    analyzer = NetworkSVDAnalyzer(
        n_nodes=50, 
        connection_prob=0.12, 
        attack_budget=0.25,
        use_cache=True,
        cache_ttl=60
    )
    
    # Phase 1: SVD optimisée (Randomized pour n > 100)
    singular_values, variance_ratio = analyzer.perform_svd_decomposition()
    
    # Phase 2: Vulnérabilités (avec cache L3)
    vulnerabilities = analyzer.analyze_vulnerabilities(use_cache_l3=True)
    
    # Phase 3: Perturbations stochastiques (option parallèle)
    perturbations, impacts = analyzer.model_stochastic_perturbations(
        n_perturbations=200, 
        parallel=False
    )
    
    # Phase 4: Reconstruction (A3 corrigé: seuil 90ème percentile)
    if variance_ratio is not None:
        k_optimal = np.argmax(np.cumsum(variance_ratio) > 0.90) + 1
    else:
        k_optimal = 5
    adj_reconstructed, G_reconstructed, variance = analyzer.reconstruct_reduced_network(k=k_optimal)
    
    # Visualisation
    create_dashboard(analyzer, perturbations, impacts, adj_reconstructed, G_reconstructed, variance)
    
    print("\\n" + "=" * 60)
    print("ANALYSE COMPLÉTÉE - v3.0 Final")
    print("=" * 60)



