
# Generate the corrected optimized_offensive_engine.py
# Changes: A1 (reward normalization by degree, state normalization), A2 (replay buffer, adversarial retraining loop), 
# Bug fix: transfer_efficiency inverted logic

"""
Optimized Offensive SVD/PCA Engine v3.0 (Final)
================================================
Moteur d'analyse de réseau haute performance avec:
- Décomposition SVD Randomized (Halko et al.)
- Cache hiérarchique L1/L2/L3
- Détection non-linéaire (Kernel PCA + XGBoost + Ensemble)
- Évasion par Apprentissage par Renforcement (PPO) — A1 corrigé
- IDS dynamique avec online learning (ADWIN) — A2 corrigé
- Attaques par Transfer Learning (Procrustes + GAN)
- Replay Buffer pour adversarial retraining (A2)
- Reward normalisée par degré local (A1)

Auteur: Generated by AI
Date: 2026-05-31
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Circle
import seaborn as sns
from sklearn.decomposition import PCA, KernelPCA
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import IsolationForest
from sklearn.neighbors import LocalOutlierFactor
from sklearn.utils.extmath import randomized_svd
from scipy.linalg import svd
from scipy.sparse import csr_matrix
from scipy.sparse.linalg import svds, eigs
from scipy.stats import entropy
import networkx as nx
from dataclasses import dataclass, field
from typing import List, Tuple, Dict, Optional
from collections import defaultdict, deque, OrderedDict
import warnings
import time
import hashlib
import os
import json

warnings.filterwarnings('ignore')
plt.style.use('seaborn-v0_8-whitegrid')
sns.set_palette("husl")


# ═══════════════════════════════════════════════════════════════════════════════
# CACHE HIÉRARCHIQUE (Partagé)
# ═══════════════════════════════════════════════════════════════════════════════

class HierarchicalCache:
    """Cache hiérarchique L1 (RAM) / L2 (Disque) / L3 (Précalculs)"""
    
    def __init__(self, ttl=60, l2_path='./cache_l2', max_l1_size=100):
        self.l1 = OrderedDict()
        self.l1_timestamps = {}
        self.l1_access_count = {}
        self.ttl = ttl
        self.max_l1_size = max_l1_size
        self.l2_path = l2_path
        self.l3 = {}
        
        # Correction Hit Rate
        self.hits = 0
        self.misses = 0
        
        os.makedirs(l2_path, exist_ok=True)
        
    def _hash_key(self, matrix_type, k, matrix_data):
        data_hash = hashlib.md5(matrix_data.tobytes()).hexdigest()[:16]
        return f"{matrix_type}_k{k}_{data_hash}"
    
    def get(self, matrix_type, k, matrix_data):
        key = self._hash_key(matrix_type, k, matrix_data)
        
        if key in self.l1:
            if time.time() - self.l1_timestamps.get(key, 0) < self.ttl:
                self.l1.move_to_end(key)
                self.l1_access_count[key] = self.l1_access_count.get(key, 0) + 1
                self.hits += 1
                return self.l1[key]
            else:
                del self.l1[key]
                del self.l1_timestamps[key]
                del self.l1_access_count[key]
        
        l2_file = os.path.join(self.l2_path, f"{key}.npz")
        if os.path.exists(l2_file):
            data = np.load(l2_file, allow_pickle=True)
            result = (data['U'], data['S'], data['Vt'])
            self._put_l1(key, result)
            self.hits += 1
            return result
        
        self.misses += 1
        return None
    
    def put(self, matrix_type, k, matrix_data, result):
        key = self._hash_key(matrix_type, k, matrix_data)
        self._put_l1(key, result)
        self._put_l2(key, result)
    
    def _put_l1(self, key, result):
        self.l1[key] = result
        self.l1_timestamps[key] = time.time()
        self.l1_access_count[key] = 1
        self.l1.move_to_end(key)
        while len(self.l1) > self.max_l1_size:
            oldest = next(iter(self.l1))
            del self.l1[oldest]
            del self.l1_timestamps[oldest]
            del self.l1_access_count[oldest]
    
    def _put_l2(self, key, result):
        l2_file = os.path.join(self.l2_path, f"{key}.npz")
        U, S, Vt = result
        np.savez_compressed(l2_file, U=U, S=S, Vt=Vt)
    
    def preload_l3(self, engine):
        print("Précalcul des centralités (Cache L3)...")
        self.l3['eigenvector'] = nx.eigenvector_centrality(engine.G, weight='weight', max_iter=1000)
        # Optimisation: Betweenness avec échantillonnage k=50 pour accélérer
        self.l3['betweenness'] = nx.betweenness_centrality(engine.G, weight='weight', k=50 if len(engine.G) > 100 else None)
        self.l3['closeness'] = nx.closeness_centrality(engine.G)
        self.l3['pagerank'] = nx.pagerank(engine.G, weight='weight')
        self.l3['degree'] = dict(engine.G.degree(weight='weight'))
        print(f"Cache L3 prêt: {len(self.l3)} métriques.")
    
    def get_l3(self, metric_name):
        return self.l3.get(metric_name, {})
    
    def stats(self):
        """Retourne les statistiques du cache (Correction Hit Rate)"""
        total_access = self.hits + self.misses
        hit_rate = self.hits / total_access if total_access > 0 else 0.0
        return {
            'l1_size': len(self.l1),
            'l2_files': len([f for f in os.listdir(self.l2_path) if f.endswith('.npz')]),
            'l3_metrics': len(self.l3),
            'l1_hit_rate': hit_rate
        }


# ═══════════════════════════════════════════════════════════════════════════════
# MOTEUR SVD RANDOMIZED OPTIMISÉ
# ═══════════════════════════════════════════════════════════════════════════════

class OptimizedSVDEngine:
    """
    Moteur SVD v3.0 avec:
    - SVD Randomized (Halko et al.) pour grands réseaux
    - Cache hiérarchique L1/L2/L3
    - Mise à jour incrémentale (Brand)
    - Parallélisation optionnelle
    """
    
    def __init__(self, n_nodes: int = 200, connection_prob: float = 0.08, 
                 seed: int = 42, use_sparse: bool = True, use_cache: bool = True):
        self.n_nodes = n_nodes
        self.use_sparse = use_sparse and n_nodes > 100
        self.seed = seed
        self.use_cache = use_cache
        np.random.seed(seed)
        
        # Génération du réseau
        self.G = self._generate_advanced_network()
        self.adj_matrix = nx.to_numpy_array(self.G, weight='weight')
        
        # Cache
        self.cache = HierarchicalCache() if use_cache else None
        self._svd_cache = {}  # Cache interne legacy
        self._update_queue = deque(maxlen=100)
        
        # Laplaciens
        self.laplacian = None
        self.normalized_laplacian = None
        self._compute_laplacians()
        
        # Attributs SVD
        self.U = None
        self.S = None
        self.Vt = None
        
        # Précalculs L3
        if self.cache:
            self.cache.preload_l3(self)
        
    def _generate_advanced_network(self):
        """Génère un réseau réaliste avec communautés et hubs"""
        G = nx.Graph()
        G.add_nodes_from(range(self.n_nodes))
        
        n_communities = max(3, self.n_nodes // 30)
        community_size = self.n_nodes // n_communities
        
        for c in range(n_communities):
            start = c * community_size
            end = min((c + 1) * community_size, self.n_nodes)
            size = end - start
            subG = nx.watts_strogatz_graph(size, k=min(6, size-1), p=0.3, seed=self.seed+c)
            mapping = {i: start + i for i in range(size)}
            subG = nx.relabel_nodes(subG, mapping)
            G.add_edges_from(subG.edges())
        
        bridge_nodes = [c * community_size for c in range(n_communities)]
        for i, node_a in enumerate(bridge_nodes):
            for j, node_b in enumerate(bridge_nodes):
                if i < j and np.random.random() < 0.7:
                    G.add_edge(node_a, node_b, weight=np.random.uniform(3.0, 8.0))
        
        critical_nodes = [0, community_size, 2*community_size]
        for node in critical_nodes:
            targets = np.random.choice(
                [n for n in G.nodes() if n != node], 
                size=min(15, self.n_nodes//3), replace=False
            )
            for target in targets:
                if not G.has_edge(node, target):
                    G.add_edge(node, target, weight=np.random.uniform(2.0, 10.0))
        
        betweenness = nx.betweenness_centrality(G)
        for u, v in G.edges():
            bw = (betweenness[u] + betweenness[v]) / 2
            G[u][v]['weight'] = G[u][v].get('weight', 1.0) * (1 + 5 * bw)
        
        return G
    
    def _compute_laplacians(self):
        self.laplacian = nx.laplacian_matrix(self.G, weight='weight').toarray()
        degrees = np.array([self.G.degree(n, weight='weight') for n in self.G.nodes()])
        D_inv_sqrt = np.diag(1.0 / np.sqrt(degrees + 1e-10))
        self.normalized_laplacian = D_inv_sqrt @ self.laplacian @ D_inv_sqrt
    
    def compute_fast_svd(self, k: int = None, matrix_type: str = 'adjacency', use_cache: bool = True):
        """SVD optimisé avec Randomized + Cache hiérarchique"""
        k = k or min(self.n_nodes // 4, 50)
        
        # Cache hiérarchique
        if use_cache and self.cache and matrix_type == 'adjacency':
            cached = self.cache.get(matrix_type, k, self.adj_matrix)
            if cached is not None:
                self.U, self.S, self.Vt = cached
                return cached
        
        # Cache legacy
        cache_key = f"{matrix_type}_{k}"
        if use_cache and cache_key in self._svd_cache:
            U, S, Vt = self._svd_cache[cache_key]
            if matrix_type == 'adjacency':
                self.U, self.S, self.Vt = U, S, Vt
            return U, S, Vt
        
        if matrix_type == 'adjacency':
            M = self.adj_matrix
        elif matrix_type == 'laplacian':
            M = self.laplacian
        elif matrix_type == 'normalized_laplacian':
            M = self.normalized_laplacian
        else:
            raise ValueError(f"Type inconnu: {matrix_type}")
        
        n = M.shape[0]
        
        # Sélection intelligente de l'algorithme
        if n > 100 and k < n // 2:
            # SVD Randomized (Halko et al.) - O(nk²)
            U, S, Vt = randomized_svd(
                M, n_components=k, 
                n_oversamples=10,
                power_iteration_normalizer='QR',
                random_state=self.seed
            )
        elif self.use_sparse and n > 100:
            M_sparse = csr_matrix(M)
            U, S, Vt = svds(M_sparse, k=k, which='LM')
            idx = np.argsort(S)[::-1]
            U, S, Vt = U[:, idx], S[idx], Vt[idx, :]
        else:
            U, S, Vt = svd(M, full_matrices=False)
            U, S, Vt = U[:, :k], S[:k], Vt[:k, :]
        
        if matrix_type == 'adjacency':
            self.U, self.S, self.Vt = U, S, Vt
        
        # Stocker dans les caches
        if use_cache:
            self._svd_cache[cache_key] = (U, S, Vt)
            if self.cache and matrix_type == 'adjacency':
                self.cache.put(matrix_type, k, self.adj_matrix, (U, S, Vt))
        
        return U, S, Vt
    
    def incremental_svd_update(self, edge_changes: List[Tuple[int, int, float]], k: int = None):
        """Mise à jour incrémentale du SVD (algorithme de Brand amélioré)"""
        if k is None:
            k = len(self.S) if self.S is not None else min(self.n_nodes//4, 50)
        
        U, S, Vt = self.compute_fast_svd(k=k)
        
        for u, v, delta in edge_changes:
            a = np.zeros(self.n_nodes); a[u] = delta
            b = np.zeros(self.n_nodes); b[v] = 1.0
            
            m = U.T @ a
            p = a - U @ m
            p_norm = np.linalg.norm(p)
            P = p / p_norm if p_norm > 1e-9 else np.zeros_like(p)
            
            n_vec = Vt @ b
            q = b - Vt.T @ n_vec
            q_norm = np.linalg.norm(q)
            Q = q / q_norm if q_norm > 1e-9 else np.zeros_like(q)
            
            K_mat = np.zeros((k + 1, k + 1))
            K_mat[:k, :k] = np.diag(S)
            col_vec = np.append(m, p_norm)
            row_vec = np.append(n_vec, q_norm)
            K_mat += np.outer(col_vec, row_vec)
            
            Uk, Sk, Vtk = svd(K_mat, full_matrices=False)
            U_new = np.column_stack((U, P)) @ Uk
            Vt_new = Vtk @ np.vstack((Vt, Q))
            
            U = U_new[:, :k]
            S = Sk[:k]
            Vt = Vt_new[:k, :]
        
        self.U, self.S, self.Vt = U, S, Vt
        cache_key = f"adjacency_{k}"
        self._svd_cache[cache_key] = (U, S, Vt)
        for key in list(self._svd_cache.keys()):
            if not key.endswith(str(k)):
                self._svd_cache.pop(key)
        
        return S
    
    def extract_spectral_features(self):
        """Extraction de caractéristiques spectrales avancées"""
        U, S, Vt = self.compute_fast_svd(k=min(self.n_nodes//2, 100))
        features = {
            'spectral_gap': S[0] - S[1] if len(S) > 1 else 0,
            'effective_rank': int(np.sum(S / S[0] > 0.01)),
            'entropy': float(-np.sum((S**2 / np.sum(S**2)) * np.log(S**2 / np.sum(S**2) + 1e-10))),
            'condition_number': float(S[0] / S[-1]) if S[-1] > 1e-10 else float('inf'),
            'participation_ratio': float(np.sum(S**2)**2 / np.sum(S**4)),
        }
        eigvals, eigvecs = eigs(csr_matrix(self.normalized_laplacian), k=10, which='SM')
        features['fiedler_value'] = float(np.real(eigvals[1])) if len(eigvals) > 1 else 0
        features['community_structure'] = float(np.std(np.real(eigvecs[:, 1])))
        return features


# ═══════════════════════════════════════════════════════════════════════════════
# DÉTECTION NON-LINÉAIRE (Kernel PCA + Ensemble)
# ═══════════════════════════════════════════════════════════════════════════════

class NonlinearDetector:
    """
    Détecteur d'anomalies avancé avec:
    - Kernel PCA pour patterns non-linéaires
    - Ensemble: Isolation Forest + LOF + reconstruction error
    - Vote majoritaire adaptatif
    """
    
    def __init__(self, engine: OptimizedSVDEngine):
        self.engine = engine
        self.kpca = None
        self.iso_forest = None
        self.lof = None
        self.kpca_threshold = None
        
    def fit(self, node_embeddings):
        """Entraîne les détecteurs sur les embeddings"""
        # Kernel PCA avec noyau RBF
        self.kpca = KernelPCA(
            n_components=10, 
            kernel='rbf', 
            gamma=0.1, 
            fit_inverse_transform=True,
            random_state=42
        )
        self.kpca.fit(node_embeddings)
        
        # Calcul du seuil de reconstruction
        kpca_projection = self.kpca.transform(node_embeddings)
        reconstruction = self.kpca.inverse_transform(kpca_projection)
        kpca_errors = np.linalg.norm(node_embeddings - reconstruction, axis=1)
        self.kpca_threshold = np.percentile(kpca_errors, 90)
        
        # Isolation Forest amélioré
        self.iso_forest = IsolationForest(
            contamination=0.1, 
            random_state=42, 
            n_estimators=200,
            max_samples='auto'
        )
        self.iso_forest.fit(node_embeddings)
        
        # Local Outlier Factor (mode novelty)
        self.lof = LocalOutlierFactor(
            n_neighbors=10, 
            contamination=0.1, 
            novelty=True
        )
        self.lof.fit(node_embeddings)
        
    def predict(self, node_embeddings):
        """Prédit les anomalies avec vote majoritaire"""
        # Kernel PCA reconstruction error
        kpca_projection = self.kpca.transform(node_embeddings)
        reconstruction = self.kpca.inverse_transform(kpca_projection)
        kpca_errors = np.linalg.norm(node_embeddings - reconstruction, axis=1)
        kpca_anomaly = kpca_errors > self.kpca_threshold
        
        # Isolation Forest
        if_anomaly = self.iso_forest.predict(node_embeddings) == -1
        
        # LOF
        lof_anomaly = self.lof.predict(node_embeddings) == -1
        
        # Vote majoritaire (au moins 2 sur 3)
        ensemble_vote = (kpca_anomaly.astype(int) + if_anomaly.astype(int) + lof_anomaly.astype(int)) >= 2
        
        return ensemble_vote
    
    def anomaly_scores(self, node_embeddings):
        """Retourne les scores d'anomalie continus"""
        kpca_projection = self.kpca.transform(node_embeddings)
        reconstruction = self.kpca.inverse_transform(kpca_projection)
        kpca_errors = np.linalg.norm(node_embeddings - reconstruction, axis=1)
        
        if_scores = -self.iso_forest.score_samples(node_embeddings)
        lof_scores = -self.lof.score_samples(node_embeddings)
        
        # Normalisation et combinaison
        kpca_norm = (kpca_errors - np.min(kpca_errors)) / (np.max(kpca_errors) - np.min(kpca_errors) + 1e-10)
        if_norm = (if_scores - np.min(if_scores)) / (np.max(if_scores) - np.min(if_scores) + 1e-10)
        lof_norm = (lof_scores - np.min(lof_scores)) / (np.max(lof_scores) - np.min(lof_scores) + 1e-10)
        
        return (kpca_norm + if_norm + lof_norm) / 3.0


# ═══════════════════════════════════════════════════════════════════════════════
# INTELLIGENCE OFFENSIVE PROACTIVE v3.0
# ═══════════════════════════════════════════════════════════════════════════════

@dataclass
class AttackSurface:
    """Surface d'attaque identifiée par analyse spectrale"""
    node_id: int
    attack_vector: str
    exploitability_score: float
    impact_score: float
    detection_probability: float
    optimal_perturbation: np.ndarray = field(default_factory=lambda: np.array([]))
    evasion_strategy: str = ""
    time_to_compromise: float = 0.0


class OffensiveIntelligenceEngine:
    """Moteur d'intelligence offensive proactive v3.0"""
    
    def __init__(self, svd_engine: OptimizedSVDEngine):
        self.engine = svd_engine
        self.attack_surfaces: List[AttackSurface] = []
        self.threat_model = {
            'network_layer': {
                'ddos': {'cost': 0.3, 'stealth': 0.2, 'impact': 0.9},
                'mitm': {'cost': 0.5, 'stealth': 0.7, 'impact': 0.8},
                'routing_hijack': {'cost': 0.6, 'stealth': 0.6, 'impact': 0.85},
            },
            'spectral_layer': {
                'eigenvector_poisoning': {'cost': 0.2, 'stealth': 0.9, 'impact': 0.6},
                'svd_perturbation': {'cost': 0.3, 'stealth': 0.85, 'impact': 0.75},
                'community_deception': {'cost': 0.4, 'stealth': 0.8, 'impact': 0.7},
            }
        }
        self.detection_model = {
            'pca_components': 5,
            'threshold_zscore': 2.5,
        }
        self.nonlinear_detector = None
    
    def proactive_vulnerability_scan(self, use_nonlinear: bool = True, use_parallel: bool = False):
        """Scan proactif avec détection non-linéaire optionnelle et parallélisation"""
        U, S, Vt = self.engine.compute_fast_svd(k=min(self.engine.n_nodes//3, 60))
        
        # Centralités depuis le cache L3
        if self.engine.cache and 'eigenvector' in self.engine.cache.l3:
            eigen_centrality = self.engine.cache.get_l3('eigenvector')
            betweenness = self.engine.cache.get_l3('betweenness')
            closeness = self.engine.cache.get_l3('closeness')
            pagerank = self.engine.cache.get_l3('pagerank')
        else:
            eigen_centrality = nx.eigenvector_centrality(self.engine.G, weight='weight', max_iter=1000)
            betweenness = nx.betweenness_centrality(self.engine.G, weight='weight')
            closeness = nx.closeness_centrality(self.engine.G)
            pagerank = nx.pagerank(self.engine.G, weight='weight')
        
        # Vulnérabilité spectrale
        spectral_contributions = (U[:, :5] ** 2) * S[:5]
        spectral_vulnerability = np.sum(spectral_contributions, axis=1) / np.sum(S[:5])
        
        node_embeddings = U[:, :10] * S[:10]
        
        # Détection d'anomalies
        if use_nonlinear:
            self.nonlinear_detector = NonlinearDetector(self.engine)
            self.nonlinear_detector.fit(node_embeddings)
            anomaly_scores = self.nonlinear_detector.anomaly_scores(node_embeddings)
            anomaly_flags = anomaly_scores > np.percentile(anomaly_scores, 90)
        else:
            iso_forest = IsolationForest(contamination=0.1, random_state=42)
            anomaly_flags = iso_forest.fit_predict(node_embeddings) == -1
        
        # Degré moyen pour référence
        mean_degree = np.mean([d for n, d in self.engine.G.degree()])
        
        # A4: Parallélisation du scan de vulnérabilités
        if use_parallel and self.engine.n_nodes > 50:
            try:
                from joblib import Parallel, delayed
                
                def _compute_surface(node, eigen_centrality, betweenness, closeness, pagerank,
                                     spectral_vulnerability, anomaly_flags, mean_degree, U, S, Vt):
                    vuln_score = (
                        0.20 * eigen_centrality.get(node, 0) +
                        0.25 * betweenness.get(node, 0) +
                        0.10 * closeness.get(node, 0) +
                        0.15 * pagerank.get(node, 0) +
                        0.20 * spectral_vulnerability[node] +
                        0.10 * anomaly_flags[node]
                    )
                    attack_vector, evasion_strategy = self._optimize_attack_vector(
                        node, vuln_score, spectral_vulnerability[node], 
                        eigen_centrality.get(node, 0), betweenness.get(node, 0), mean_degree
                    )
                    optimal_pert = self._generate_optimal_perturbation(node, U, S, Vt)
                    
                    return AttackSurface(
                        node_id=node,
                        attack_vector=attack_vector,
                        exploitability_score=vuln_score,
                        impact_score=self._calculate_impact(attack_vector),
                        detection_probability=self._estimate_detection(optimal_pert),
                        optimal_perturbation=optimal_pert,
                        evasion_strategy=evasion_strategy,
                        time_to_compromise=self._estimate_ttc(attack_vector)
                    )
                
                self.attack_surfaces = Parallel(n_jobs=-1, prefer="threads")(
                    delayed(_compute_surface)(
                        node, eigen_centrality, betweenness, closeness, pagerank,
                        spectral_vulnerability, anomaly_flags, mean_degree, U, S, Vt
                    )
                    for node in range(self.engine.n_nodes)
                )
            except ImportError:
                use_parallel = False
        
        if not use_parallel:
            self.attack_surfaces = []
            for node in range(self.engine.n_nodes):
                vuln_score = (
                    0.20 * eigen_centrality.get(node, 0) +
                    0.25 * betweenness.get(node, 0) +
                    0.10 * closeness.get(node, 0) +
                    0.15 * pagerank.get(node, 0) +
                    0.20 * spectral_vulnerability[node] +
                    0.10 * anomaly_flags[node]
                )
                
                attack_vector, evasion_strategy = self._optimize_attack_vector(
                    node, vuln_score, spectral_vulnerability[node], 
                    eigen_centrality.get(node, 0), betweenness.get(node, 0), mean_degree
                )
                
                optimal_pert = self._generate_optimal_perturbation(node, U, S, Vt)
                
                surface = AttackSurface(
                    node_id=node,
                    attack_vector=attack_vector,
                    exploitability_score=vuln_score,
                    impact_score=self._calculate_impact(attack_vector),
                    detection_probability=self._estimate_detection(optimal_pert),
                    optimal_perturbation=optimal_pert,
                    evasion_strategy=evasion_strategy,
                    time_to_compromise=self._estimate_ttc(attack_vector)
                )
                self.attack_surfaces.append(surface)
        
        self.attack_surfaces.sort(key=lambda x: x.exploitability_score, reverse=True)
        return self.attack_surfaces
    
    def _optimize_attack_vector(self, node, vuln_score, spectral_score, eigen_score, between_score, mean_degree):
        # Correction : Baisser les seuils et multiplier les conditions pour diversifier les attaques
        if spectral_score > 0.5 and eigen_score > 0.3:
            return "eigenvector_poisoning", "Perturbation espace nul SVD + camouflage spectral"
        elif vuln_score > 0.25 and between_score > 0.2:
            return "svd_perturbation", "Injection orthogonale PCA IDS"
        elif nx.degree(self.engine.G, node) > (mean_degree * 1.5):  # Plus restrictif sur le degré
            return "routing_hijack", "Manipulation métriques routage"
        else:
            return "community_deception", "Migration artificielle communautés"
    
    def _generate_optimal_perturbation(self, target_node, U, S, Vt):
        n = self.engine.n_nodes
        k_ids = self.detection_model['pca_components']
        U_null = U[:, k_ids:]
        e_target = np.zeros(n); e_target[target_node] = 1.0
        pert_null = U_null @ U_null.T @ e_target
        if np.linalg.norm(pert_null) > 1e-10:
            pert_null = pert_null / np.linalg.norm(pert_null)
        return pert_null * 0.25 * S[0]
    
    def _calculate_impact(self, attack_vector):
        for layer, vectors in self.threat_model.items():
            if attack_vector in vectors:
                return vectors[attack_vector]['impact']
        return 0.5
    
    def _estimate_detection(self, perturbation):
        U, S, Vt = self.engine.compute_fast_svd(k=10)
        U_mon = U[:, :self.detection_model['pca_components']]
        projection = np.linalg.norm(U_mon.T @ perturbation)
        return 1 / (1 + np.exp(-2 * (projection - self.detection_model['threshold_zscore'])))
    
    def _estimate_ttc(self, attack_vector):
        base_time = {'eigenvector_poisoning': 2.0, 'svd_perturbation': 1.5,
                     'routing_hijack': 3.0, 'community_deception': 4.0}
        return base_time.get(attack_vector, 5.0) * (1 + np.random.random())


# ═══════════════════════════════════════════════════════════════════════════════
# ÉVASION PAR APPRENTISSAGE PAR RENFORCEMENT (PPO) — A1 CORRIGÉ
# ═══════════════════════════════════════════════════════════════════════════════

class PPOEvasionAgent:
    """
    Agent PPO pour optimisation des stratégies d'évasion.
    A1 CORRECTIONS:
    - Reward normalisée par log(1 + degree(target))
    - État normalisé par statistiques locales du sous-graphe ego
    """
    
    def __init__(self, state_dim=10, action_dim=3, lr=0.001, gamma=0.99, epsilon=0.1):
        self.state_dim = state_dim
        self.action_dim = action_dim
        self.lr = lr
        self.gamma = gamma
        self.epsilon = epsilon
        
        # Réseaux de neurones simples (policy et value)
        self.policy_weights = np.random.randn(state_dim, action_dim) * 0.01
        self.value_weights = np.random.randn(state_dim, 1) * 0.01
        
        # Mémoire d'expérience
        self.memory = []
        
        # A1: Statistiques de normalisation d'état
        self.state_mean = 0.0
        self.state_std = 1.0
        
    def normalize_state(self, state):
        """A1: Normalise l'état par les statistiques locales du nœud cible"""
        return (state - self.state_mean) / self.state_std
    
    def set_normalization_stats(self, mean, std):
        """A1: Définit les statistiques de normalisation pour le nœud cible"""
        self.state_mean = mean
        self.state_std = np.where(std > 1e-8, std, 1.0)
        
    def select_action(self, state):
        """Sélectionne une action selon la policy actuelle (softmax)"""
        # A1: Normalisation d'état avant décision
        norm_state = self.normalize_state(state)
        logits = norm_state @ self.policy_weights
        logits = logits - np.max(logits)  # Stabilité numérique
        probs = np.exp(logits)
        probs = probs / np.sum(probs)
        
        if np.random.random() < self.epsilon:
            return np.random.randint(self.action_dim)
        else:
            return np.argmax(probs)
    
    def store_transition(self, state, action, reward, next_state, done):
        """Stocke une transition dans la mémoire d'expérience"""
        self.memory.append((state, action, reward, next_state, done))
    
    def compute_advantages(self, rewards, values, gamma=0.99, lam=0.95):
        """Calcule les avantages généralisés (GAE)"""
        advantages = np.zeros_like(rewards)
        last_advantage = 0
        
        for t in reversed(range(len(rewards))):
            if t == len(rewards) - 1:
                next_value = 0
            else:
                next_value = values[t + 1]
            
            delta = rewards[t] + gamma * next_value - values[t]
            advantages[t] = delta + gamma * lam * last_advantage
            last_advantage = advantages[t]
        
        return advantages
    
    def update(self, batch_size=32):
        """Met à jour la policy avec PPO (simplifié)"""
        if len(self.memory) < batch_size:
            return
        
        # Échantillonner un batch
        batch = self.memory[:batch_size]
        states = np.array([m[0] for m in batch])
        actions = np.array([m[1] for m in batch])
        rewards = np.array([m[2] for m in batch])
        
        # Calculer les valeurs
        values = states @ self.value_weights
        values = values.flatten()
        
        # Calculer les avantages
        advantages = self.compute_advantages(rewards, values)
        advantages = (advantages - np.mean(advantages)) / (np.std(advantages) + 1e-10)
        
        # Mise à jour policy (gradient ascent avec clipping PPO)
        for i in range(batch_size):
            state = states[i]
            action = actions[i]
            advantage = advantages[i]
            
            logits = state @ self.policy_weights
            logits = logits - np.max(logits)
            probs = np.exp(logits)
            probs = probs / np.sum(probs)
            
            old_prob = probs[action]
            
            # Gradient policy
            grad = np.zeros_like(self.policy_weights)
            for a in range(self.action_dim):
                if a == action:
                    grad[:, a] = state * (1 - probs[a]) * advantage
                else:
                    grad[:, a] = -state * probs[a] * advantage
            
            # Clipping PPO
            ratio = probs[action] / (old_prob + 1e-10)
            clipped_ratio = np.clip(ratio, 0.8, 1.2)
            
            self.policy_weights += self.lr * grad * (1 if ratio < clipped_ratio else 0)
        
        # Mise à jour value function
        for i in range(batch_size):
            state = states[i]
            target_value = rewards[i]
            value_pred = state @ self.value_weights
            value_error = target_value - value_pred
            self.value_weights += self.lr * value_error * state.reshape(-1, 1)
        
        self.memory = []


# ═══════════════════════════════════════════════════════════════════════════════
# IDS DYNAMIQUE AVEC ONLINE LEARNING — A2 CORRIGÉ
# ═══════════════════════════════════════════════════════════════════════════════

class ADWINDetector:
    """Détecteur de concept drift ADWIN (ADaptive WINdowing)"""
    
    def __init__(self, delta=0.002):
        self.delta = delta
        self.window = []
        
    def detect_drift(self, data_stream):
        """Détecte un changement dans le flux de données"""
        if len(data_stream) < 10:
            return False
        
        mid = len(data_stream) // 2
        mean1 = np.mean(data_stream[:mid])
        mean2 = np.mean(data_stream[mid:])
        std = np.std(data_stream)
        
        if std == 0:
            return False
        
        z_score = abs(mean1 - mean2) / (std / np.sqrt(len(data_stream)))
        return z_score > 2.5


class DynamicIDS:
    """
    IDS dynamique avec:
    - Online learning
    - Détection de concept drift (ADWIN)
    - Randomisation adaptative des seuils
    - Rotation d'ensemble de détecteurs
    - A2: Replay buffer pour adversarial retraining
    """
    
    def __init__(self, threshold=2.5, adaptation_rate=0.1, replay_buffer_size=5000):
        self.threshold = threshold
        self.base_threshold = threshold
        self.adaptation_rate = adaptation_rate
        self.detection_history = []
        self.drift_detector = ADWINDetector()
        self.false_positive_rate = 0.05
        self.active_detector = 0
        self.detectors = [
            {'name': 'PCA', 'threshold': threshold},
            {'name': 'Kernel', 'threshold': threshold * 1.2},
            {'name': 'Ensemble', 'threshold': threshold * 0.8},
        ]
        
        # A2: Replay buffer pour adversarial retraining
        self.replay_buffer = deque(maxlen=replay_buffer_size)
        self.episode_count = 0
        
    def detect(self, score):
        """Détecte une intrusion avec seuil adaptatif et rotation"""
        # Rotation des détecteurs
        detector = self.detectors[self.active_detector]
        
        # Randomisation du seuil
        noise = np.random.normal(0, detector['threshold'] * 0.05)
        effective_threshold = detector['threshold'] + noise
        
        detected = score > effective_threshold
        self.detection_history.append((score, detected))
        
        # Détection de concept drift
        if len(self.detection_history) > 20:
            recent_scores = [s for s, d in self.detection_history[-20:]]
            if self.drift_detector.detect_drift(recent_scores):
                self._adapt_threshold()
                self.active_detector = (self.active_detector + 1) % len(self.detectors)
        
        # Limiter l'historique
        if len(self.detection_history) > 1000:
            self.detection_history = self.detection_history[-500:]
        
        return detected
    
    def add_to_replay(self, perturbation, detected, episode):
        """A2: Ajoute une perturbation au replay buffer pour retraining"""
        self.replay_buffer.append({
            'perturbation': perturbation,
            'detected': detected,
            'episode': episode,
            'timestamp': time.time()
        })
        self.episode_count = episode
    
    def should_retrain(self, retrain_interval=20, min_samples=500):
        """A2: Détermine si l'IDS doit être retrainé sur les évasions récentes"""
        return (self.episode_count > 0 and 
                self.episode_count % retrain_interval == 0 and 
                len(self.replay_buffer) >= min_samples)
    
    def get_adversarial_batch(self, batch_size=100):
        """A2: Retourne un batch de perturbations récentes pour retraining"""
        if len(self.replay_buffer) < batch_size:
            return []
        # Sélectionner les perturbations qui ont échappé à la détection (évasions réussies)
        evasions = [item for item in self.replay_buffer if not item['detected']]
        if len(evasions) < batch_size // 2:
            # Pas assez d'évasions, prendre toutes les perturbations récentes
            recent = list(self.replay_buffer)[-batch_size:]
            return [item['perturbation'] for item in recent]
        return [item['perturbation'] for item in evasions[-batch_size:]]
    
    def retrain(self, perturbations):
        """A2: Met à jour les seuils basés sur les perturbations adversariales récentes"""
        if len(perturbations) == 0:
            return
        
        # Calculer les scores de détection pour les perturbations adversariales
        scores = [np.linalg.norm(p) for p in perturbations]
        if len(scores) > 0:
            new_threshold = np.percentile(scores, 95) * 1.2
            for det in self.detectors:
                det['threshold'] = new_threshold * (1 + np.random.uniform(-0.1, 0.1))
            print(f"[IDS ADVERSARIAL] Retraining effectué. Nouveau seuil: {new_threshold:.3f}")
    
    def _adapt_threshold(self):
        """Adapte le seuil en cas de drift détecté"""
        recent_scores = [s for s, d in self.detection_history[-50:]]
        new_threshold = np.percentile(recent_scores, 95) * 1.2
        
        for det in self.detectors:
            det['threshold'] = new_threshold * (1 + np.random.uniform(-0.1, 0.1))
        
        print(f"[IDS DYNAMIQUE] Seuil adapté: {new_threshold:.3f} (détecteur: {self.detectors[self.active_detector]['name']})")


# ═══════════════════════════════════════════════════════════════════════════════
# SIMULATEUR D'ÉVASION IDS v3.0 — A1 + A2 CORRIGÉS
# ═══════════════════════════════════════════════════════════════════════════════

class AdvancedIDSEvasionSimulator:
    """Simulateur d'évasion IDS v3.0 avec RL et IDS dynamique adversarial-robuste"""
    
    def __init__(self, engine: OptimizedSVDEngine, intelligence: OffensiveIntelligenceEngine):
        self.engine = engine
        self.intelligence = intelligence
        self.ids = DynamicIDS(threshold=2.5)
        self.rl_agent = PPOEvasionAgent(state_dim=10, action_dim=3, lr=0.001)
        
    def simulate_adaptive_evasion(self, target_surface, n_episodes=100, use_rl=True):
        """Simulation d'évasion avec RL optionnel — A1 corrigé"""
        results = {
            'detection_rates': [],
            'evasion_success': [],
            'perturbation_magnitudes': [],
            'ids_threshold_history': [],
            'strategies_used': [],
            'rl_rewards': []
        }
        
        optimal_pert = target_surface.optimal_perturbation.copy()
        target_node = target_surface.node_id
        
        # A1: Calculer les statistiques de normalisation locales
        local_subgraph = nx.ego_graph(self.engine.G, target_node, radius=2)
        local_degree = self.engine.G.degree(target_node)
        
        # A1: Normalisation par le sous-graphe local
        U_full, S_full, _ = self.engine.compute_fast_svd(k=10)
        local_projections = []
        for n in local_subgraph.nodes():
            local_projections.append(U_full[n, :10] * S_full[:10])
        if len(local_projections) > 0:
            local_projections = np.array(local_projections)
            state_mean = np.mean(local_projections, axis=0)
            state_std = np.std(local_projections, axis=0) + 1e-8
        else:
            state_mean = np.zeros(10)
            state_std = np.ones(10)
        
        self.rl_agent.set_normalization_stats(state_mean, state_std)
        
        for episode in range(n_episodes):
            # État pour RL (embeddings + métriques IDS)
            U, S, Vt = self.engine.compute_fast_svd(k=10)
            state = U[target_node, :10] * S[:10]
            state = state / (np.linalg.norm(state) + 1e-10)
            
            # Sélection de la stratégie
            if use_rl and episode > 10:
                action = self.rl_agent.select_action(state)
                strategies = ['direct', 'null_space', 'temporal_smoothing']
                strategy = strategies[action]
            else:
                # Exploration initiale
                if episode < n_episodes // 3:
                    strategy = 'direct'
                elif episode < 2 * n_episodes // 3:
                    strategy = 'null_space'
                else:
                    strategy = 'temporal_smoothing'
                action = ['direct', 'null_space', 'temporal_smoothing'].index(strategy)
            
            # Génération de la perturbation
            if strategy == 'direct':
                pert = optimal_pert * (1 + 0.3 * np.random.randn())
            elif strategy == 'null_space':
                U, S, Vt = self.engine.compute_fast_svd(k=15)
                U_null = U[:, 5:]
                pert = U_null @ np.random.randn(U_null.shape[1]) * 0.3
            else:
                pert = optimal_pert * np.sin(np.linspace(0, 2*np.pi, self.engine.n_nodes))
                pert = pert / (np.linalg.norm(pert) + 1e-10) * 0.25
            
            # Évaluation IDS dynamique
            detection_score = self._evaluate_detection(pert)
            detected = self.ids.detect(detection_score)
            
            # A2: Ajouter au replay buffer pour adversarial retraining
            self.ids.add_to_replay(pert, detected, episode)
            
            # A2: Retraining adversarial tous les 20 épisodes
            if self.ids.should_retrain(retrain_interval=20, min_samples=100):
                adv_batch = self.ids.get_adversarial_batch(batch_size=100)
                if len(adv_batch) > 0:
                    self.ids.retrain(adv_batch)
            
            # A1: Reward normalisée par log(1 + degree(target))
            # Pénalité forte si détecté, bonus si évasion, pénalité magnitude
            raw_reward = -1.0 if detected else 1.0
            raw_reward -= np.linalg.norm(pert) * 0.1  # Pénalité magnitude
            
            # A1: Normalisation par le degré local du nœud cible
            degree_norm = np.log(1 + local_degree)
            reward = raw_reward / degree_norm if degree_norm > 0 else raw_reward
            
            if use_rl:
                next_state = state + np.random.normal(0, 0.01, len(state))
                self.rl_agent.store_transition(state, action, reward, next_state, episode == n_episodes - 1)
                
                if episode % 10 == 0:
                    self.rl_agent.update()
            
            results['detection_rates'].append(float(detected))
            results['evasion_success'].append(float(not detected))
            results['perturbation_magnitudes'].append(np.linalg.norm(pert))
            results['ids_threshold_history'].append(self.ids.detectors[self.ids.active_detector]['threshold'])
            results['strategies_used'].append(strategy)
            results['rl_rewards'].append(reward)
        
        return results
    
    def _evaluate_detection(self, perturbation):
        """Évalue le score de détection IDS (Correction: empêche les scores négatifs)"""
        U, S, Vt = self.engine.compute_fast_svd(k=10)
        pca_projection = U[:, :5].T @ perturbation
        score = np.linalg.norm(pca_projection) / (np.std(S[:5]) + 1e-10)
        # Ajout de bruit mais avec un seuil bas à 0
        return max(0.0, score + np.random.normal(0, 0.2))
    
    def simulate_transfer_attack(self, source_surface, target_surface):
        """Attaque par transfer learning avec rotation Procrustes — BUG FIXÉ"""
        source_pert = source_surface.optimal_perturbation
        U, S, Vt = self.engine.compute_fast_svd(k=20)
        
        source_idx = source_surface.node_id
        target_idx = target_surface.node_id
        
        source_basis = U[source_idx, :10]
        target_basis = U[target_idx, :10]
        
        # Alignement de Procrustes
        M = np.outer(target_basis, source_basis)
        U_rot, _, Vt_rot = svd(M)
        R = U_rot @ Vt_rot
        
        # Rotation de la perturbation
        v_source = U[:, :10].T @ source_pert
        v_target = R @ v_source
        transferred_pert = U[:, :10] @ v_target
        
        if np.linalg.norm(transferred_pert) > 1e-10:
            transferred_pert = transferred_pert / np.linalg.norm(transferred_pert) * np.linalg.norm(source_pert)
        
        src_det = self._evaluate_detection(source_pert)
        tgt_det = self._evaluate_detection(transferred_pert)
        
        # BUG FIX: transfer_efficiency = src_det / tgt_det (pas tgt_det / src_det)
        # Si tgt_det > src_det, l'agent se dégrade → efficiency < 1
        # Si tgt_det < src_det, l'agent s'améliore → efficiency > 1
        transfer_eff = src_det / (tgt_det + 1e-10) if tgt_det > 1e-5 else 0.0
        
        return {
            'source_detection': src_det,
            'target_detection': tgt_det,
            'transfer_efficiency': transfer_eff,  # BUG FIXÉ: src/tgt au lieu de tgt/src
            'transferred_perturbation': transferred_pert,
            'rotation_matrix': R
        }


# ═══════════════════════════════════════════════════════════════════════════════
# VISUALISATION
# ═══════════════════════════════════════════════════════════════════════════════

def create_audit_dashboard(engine, surfaces, evasion_results, transfer, output_path='audit_dashboard.png'):
    """Crée le dashboard d'audit et d'optimisation v3.0"""
    
    dir_name = os.path.dirname(output_path)
    if dir_name and not os.path.exists(dir_name):
        os.makedirs(dir_name, exist_ok=True)
        
    fig = plt.figure(figsize=(24, 16))
    fig.suptitle("AUDIT & OPTIMISATION OFFENSIVE v3.0 - SVD/PCA\\n"
                 "RL Évasion (A1 corrigé), IDS Adversarial (A2), Détection Non-Linéaire", 
                 fontsize=20, fontweight='bold', y=0.98)
    
    # Panel 1: Topologie
    ax1 = fig.add_subplot(2, 3, 1)
    from sklearn.cluster import KMeans
    U_comm, _, _ = engine.compute_fast_svd(k=10, matrix_type='normalized_laplacian')
    communities = KMeans(n_clusters=5, random_state=42, n_init=10).fit_predict(U_comm[:, 1:6])
    pos = nx.spring_layout(engine.G, k=1.5, iterations=100, seed=42)
    nx.draw_networkx_edges(engine.G, pos, alpha=0.2, width=0.5, ax=ax1, edge_color='gray')
    node_sizes = [100 + 800 * s.exploitability_score for s in surfaces]
    nx.draw_networkx_nodes(engine.G, pos, node_color=communities, cmap=plt.cm.tab10,
                            node_size=node_sizes, ax=ax1, alpha=0.9, edgecolors='black', linewidths=0.5)
    top5 = [s.node_id for s in surfaces[:5]]
    nx.draw_networkx_labels(engine.G, pos, {n: str(n) for n in top5}, font_size=8, font_weight='bold', ax=ax1)
    ax1.set_title("Topologie du Réseau\\n(Communautés & Vulnérabilité)", fontsize=14, fontweight='bold')
    ax1.axis('off')
    
    # Panel 2: Spectre SVD
    ax2 = fig.add_subplot(2, 3, 2)
    U, S, Vt = engine.compute_fast_svd(k=30)
    x = np.arange(1, len(S) + 1)
    ax2.bar(x[:25], S[:25], color='steelblue', alpha=0.7)
    ax2_twin = ax2.twinx()
    cumvar = np.cumsum(S**2) / np.sum(S**2) * 100
    ax2_twin.plot(x[:25], cumvar[:25], 'ro-', linewidth=2, markersize=6)
    ax2_twin.axhline(y=85, color='green', linestyle='--', alpha=0.7)
    ax2.set_title("Spectre SVD Randomized\\n(Cache Hiérarchique)", fontsize=14, fontweight='bold')
    ax2.grid(True, alpha=0.3)
    
    # Panel 3: Surfaces d'attaque
    ax3 = fig.add_subplot(2, 3, 3)
    exploit_scores = [s.exploitability_score for s in surfaces]
    impact_scores = [s.impact_score for s in surfaces]
    detect_probs = [s.detection_probability for s in surfaces]
    ttc_values = [s.time_to_compromise for s in surfaces]
    scatter = ax3.scatter(exploit_scores, impact_scores, s=[(1-d+0.1)*500 for d in detect_probs],
                           c=ttc_values, cmap='RdYlGn_r', alpha=0.7, edgecolors='black', linewidths=0.5)
    for i in range(min(5, len(surfaces))):
        s = surfaces[i]
        ax3.annotate(f'N{s.node_id}', (s.exploitability_score, s.impact_score),
                    xytext=(5, 5), textcoords='offset points', fontsize=9, fontweight='bold')
    ax3.set_title("Carte des Surfaces d'Attaque", fontsize=14, fontweight='bold')
    plt.colorbar(scatter, ax=ax3, shrink=0.8)
    
    # Panel 4: Évasion RL
    ax4 = fig.add_subplot(2, 3, 4)
    episodes = range(len(evasion_results['detection_rates']))
    ax4.plot(episodes, evasion_results['detection_rates'], 'r-', alpha=0.3, linewidth=1, label='Détection')
    ax4.plot(episodes, evasion_results['evasion_success'], 'g-', alpha=0.3, linewidth=1, label='Évasion')
    
    if 'rl_rewards' in evasion_results and evasion_results['rl_rewards']:
        rewards = np.array(evasion_results['rl_rewards'])
        rewards_smooth = np.convolve(rewards, np.ones(10)/10, mode='valid')
        ax4_twin = ax4.twinx()
        ax4_twin.plot(range(9, len(rewards)), rewards_smooth, 'b-', linewidth=2, label='Récompense RL')
        ax4_twin.set_ylabel('Récompense RL', color='blue')
        ax4_twin.tick_params(axis='y', labelcolor='blue')
    
    window = 10
    det_smooth = np.convolve(evasion_results['detection_rates'], np.ones(window)/window, mode='valid')
    succ_smooth = np.convolve(evasion_results['evasion_success'], np.ones(window)/window, mode='valid')
    ax4.plot(range(window-1, len(episodes)), det_smooth, 'r-', linewidth=2.5)
    ax4.plot(range(window-1, len(episodes)), succ_smooth, 'g-', linewidth=2.5)
    ax4.set_title("Évasion RL + IDS Adversarial (A2)", fontsize=14, fontweight='bold')
    ax4.legend(fontsize=9)
    ax4.grid(True, alpha=0.3)
    
    # Panel 5: IDS Dynamique
    ax5 = fig.add_subplot(2, 3, 5)
    if evasion_results['ids_threshold_history']:
        ax5.plot(episodes, evasion_results['ids_threshold_history'], 'purple', linewidth=2)
        ax5.fill_between(episodes, 0, evasion_results['ids_threshold_history'], alpha=0.2, color='purple')
        ax5.set_xlabel('Episode')
        ax5.set_ylabel('Seuil IDS')
        ax5.set_title("Évolution du Seuil IDS\\n(Adversarial Retraining + Drift)", fontsize=14, fontweight='bold')
        ax5.grid(True, alpha=0.3)
    
    # Panel 6: Rapport
    ax6 = fig.add_subplot(2, 3, 6)
    ax6.axis('off')
    
    cache_stats = engine.cache.stats() if engine.cache else {'l1_size': 0, 'l2_files': 0, 'l3_metrics': 0, 'l1_hit_rate': 0.0}
    
    # A1: Afficher les corrections appliquées
    perf_text = f"""
    RAPPORT D'AUDIT v3.0 — CORRECTIONS APPLIQUÉES
    ═══════════════════════════════════════════════════
    
    A1 — Transfer Learning (corrigé):
    • Reward normalisée par log(1 + degree(target))
    • État normalisé par sous-graphe ego (radius=2)
    • transfer_efficiency = src_det / tgt_det (inversé)
    
    A2 — IDS Adversarial (corrigé):
    • Replay buffer: {len(DynamicIDS().replay_buffer)} entrées
    • Retraining tous les 20 épisodes
    • Boucle co-évolution RL/IDS active
    
    A3 — Seuillage SVD (corrigé):
    • Seuil au 90ème percentile (pas moyenne)
    
    A4 — Parallélisation (activée):
    • Joblib Parallel sur scan vulnérabilités
    
    Cache:
    • L1 RAM: {cache_stats['l1_size']} entrées
    • L2 Disque: {cache_stats['l2_files']} fichiers
    • L3 Précalculs: {cache_stats['l3_metrics']} métriques
    • Hit Rate: {cache_stats['l1_hit_rate']*100:.1f}%
    
    Résultats:
    • Évasion: {np.mean(evasion_results['evasion_success'])*100:.0f}%
    • Perturbation: ε=0.25
    • Détecteurs IDS: {len(DynamicIDS().detectors)}
    """
    ax6.text(0.05, 0.95, perf_text, transform=ax6.transAxes, fontsize=10,
             verticalalignment='top', fontfamily='monospace',
             bbox=dict(boxstyle='round', facecolor='lightyellow', alpha=0.9))
    
    plt.tight_layout(rect=[0, 0, 1, 0.96])
    plt.savefig(output_path, dpi=150, bbox_inches='tight', facecolor='white')
    plt.close()
    print(f"Dashboard v3.0 sauvegardé: {output_path}")


# ═══════════════════════════════════════════════════════════════════════════════
# POINT D'ENTRÉE
# ═══════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    print("=" * 80)
    print("MOTEUR SVD/PCA v3.0 - Intelligence Proactive Optimisée (Final)")
    print("=" * 80)
    
    # Initialisation
    engine = OptimizedSVDEngine(n_nodes=150, connection_prob=0.06, seed=42, use_sparse=True, use_cache=True)
    print(f"Réseau: {engine.n_nodes} nœuds, {engine.G.number_of_edges()} arêtes")
    
    # Caractéristiques spectrales
    features = engine.extract_spectral_features()
    print(f"\\nCaractéristiques spectrales:")
    for k, v in features.items():
        if not isinstance(v, np.ndarray):
            print(f"  {k}: {v:.4f}")
    
    # Intelligence offensive
    intelligence = OffensiveIntelligenceEngine(engine)
    surfaces = intelligence.proactive_vulnerability_scan(use_nonlinear=True, use_parallel=True)
    
    print(f"\\nTop 10 Surfaces d'Attaque:")
    for i, s in enumerate(surfaces[:10]):
        print(f"  {i+1}. N{s.node_id}: {s.attack_vector} (Score: {s.exploitability_score:.3f})")
    
    # Évasion IDS avec RL (A1 corrigé)
    simulator = AdvancedIDSEvasionSimulator(engine, intelligence)
    evasion = simulator.simulate_adaptive_evasion(surfaces[0], n_episodes=100, use_rl=True)
    print(f"\\nÉvasion RL: {np.mean(evasion['evasion_success'])*100:.0f}% de succès")
    
    # Transfer learning (BUG FIXÉ)
    transfer = {}
    if len(surfaces) >= 2:
        transfer = simulator.simulate_transfer_attack(surfaces[0], surfaces[1])
        print(f"Transfert: efficacité = {transfer['transfer_efficiency']:.3f} (src={transfer['source_detection']:.3f}, tgt={transfer['target_detection']:.3f})")
    
    # Visualisation
    create_audit_dashboard(engine, surfaces, evasion, transfer)
    
    print("\\n" + "=" * 60)
    print("EXÉCUTION TERMINÉE - v3.0 Final")
    print("=" * 60)

